name: pre-commit

on:
  pull_request:
  push:
    branches: [bixin_dev]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Head
      run: |
        echo "Pull request's branch name is: ${BRANCH:-$BASE_REF}"
        git remote set-head origin "${BRANCH:-$BASE_REF}"
      env:
        BRANCH: ${{ github.head_ref }}
        BASE_REF: master
    - uses: actions/setup-python@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit test
      run: |
        git fetch origin bixin_dev
        pip install pre-commit
        pre-commit install
        pre-commit run --show-diff-on-failure --color=always --from-ref $(git merge-base HEAD origin/bixin_dev) --to-ref $(git rev-parse HEAD)
